/* DO NOT EDIT THIS FILE - it is machine generated */
#include "java\jni.h"
/* Header for class com_njucs_aiep_plugin_fir_ai_FirAICpp */

#ifndef _Included_com_njucs_aiep_plugin_fir_ai_FirAICpp
#define _Included_com_njucs_aiep_plugin_fir_ai_FirAICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    getLastGameTree
 * Signature: ()Lcom/njucs/aiep/game/GameTree;
 */
JNIEXPORT jobject JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_getLastGameTree
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    itsmyturn
 * Signature: (Lcom/njucs/aiep/plugin/fir/frame/Step;)Lcom/njucs/aiep/plugin/fir/frame/Step;
 */
JNIEXPORT jobject JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_itsmyturn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    itsmyturn2
 * Signature: (Lcom/njucs/aiep/plugin/fir/frame/Step;)Lcom/njucs/aiep/plugin/fir/frame/Step;
 */
JNIEXPORT jobject JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_itsmyturn2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    setInningInfo
 * Signature: (IILcom/njucs/aiep/net/DataTransmit/StudentInfo;[I)V
 */
JNIEXPORT void JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_setInningInfo
  (JNIEnv *, jobject, jint, jint, jobject, jintArray);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    getId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_getId
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    getNickname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_getNickname
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICpp
 * Method:    isPrintInfo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICpp_isPrintInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
