/* DO NOT EDIT THIS FILE - it is machine generated */
#include "java\jni.h"
/* Header for class com_njucs_aiep_plugin_fir_ai_FirAICSharp */

#ifndef _Included_com_njucs_aiep_plugin_fir_ai_FirAICSharp
#define _Included_com_njucs_aiep_plugin_fir_ai_FirAICSharp
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    setCurrentAIIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_setCurrentAIIndex
  (JNIEnv *env, jclass firAIClass, jint index);
/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    addFirAIDll
 * Signature: (Ljava/lang/String;)Z;
 */
JNIEXPORT jboolean JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_addFirAIDll
  (JNIEnv * env, jclass firAIClass, jstring firAIDllFileName);
/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    getLastGameTree
 * Signature: ()Lcom/njucs/aiep/game/GameTree;
 */
JNIEXPORT jobject JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_getLastGameTree
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    itsmyturn
 * Signature: (Lcom/njucs/aiep/plugin/fir/frame/Step;)Lcom/njucs/aiep/plugin/fir/frame/Step;
 */
JNIEXPORT jobject JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_itsmyturn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    itsmyturn2
 * Signature: (Lcom/njucs/aiep/plugin/fir/frame/Step;)Lcom/njucs/aiep/plugin/fir/frame/Step;
 */
JNIEXPORT jobject JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_itsmyturn2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    setInningInfo
 * Signature: (IILcom/njucs/aiep/net/DataTransmit/StudentInfo;[I)V
 */
JNIEXPORT void JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_setInningInfo
  (JNIEnv *, jobject, jint, jint, jobject, jintArray);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    getId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_getId
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    getNickname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_getNickname
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_njucs_aiep_plugin_fir_ai_FirAICSharp
 * Method:    isPrintInfo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_njucs_aiep_plugin_fir_ai_FirAICSharp_isPrintInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
